# Generated by Django 3.2 on 2024-10-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_license_plate', models.CharField(max_length=10)),
                ('route_name', models.CharField(max_length=100)),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('route_type', models.CharField(choices=[('Paved', 'Paved'), ('Paved with Potholes', 'Paved with Potholes'), ('Dirt', 'Dirt'), ('Trail', 'Trail')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('In Maintenance', 'In Maintenance')], max_length=20)),
                ('vehicle_type', models.CharField(choices=[('Bus', 'Bus'), ('Truck', 'Truck'), ('Car', 'Car'), ('SUV', 'SUV')], max_length=20)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transportation_management.route')),
            ],
        ),
    ]
