# Generated by Django 3.2.9 on 2024-10-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='route',
            new_name='route_id',
        ),
    ]
